version: "3.8"

services:
    pdf-llm-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: pdf-llm-app
        container_name: pdf-llm-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        env_file:
            - .env.prod
        environment:
            - APP_ENV=local
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        networks:
            - app-network
        user: "33:1000"
        command: ["php-fpm"]

    nginx:
        image: nginx:alpine
        container_name: my-nginx
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - pdf-llm-app
        networks:
            - app-network

    node:
        build:
            context: .
            dockerfile: Dockerfile.node
        image: pdf-llm-app-node
        container_name: pdf-llm-app-node
        ports:
            - "3000:3000"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
